name: C/C++ CI

on: [push, pull_request]

jobs:
  build-all-eigen:
    name: Build and Test RBDL + Addons
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        submodules: true
    - name: Install Build dependencies
      run: sudo apt-get install libeigen3-dev libboost-all-dev lua5.1 liblua5.1-0-dev catch2 coinor-libipopt-dev
    - name: Build project
      uses: threeal/cmake-action@v1.3.0
      with:
        options: RBDL_BUILD_ADDON_LUAMODEL=ON RBDL_BUILD_ADDON_URDFREADER=ON RBDL_BUILD_ADDON_GEOMETRY=ON RBDL_BUILD_ADDON_BALANCE=ON RBDL_BUILD_ADDON_MUSCLE=ON RBDL_BUILD_ADDON_MUSCLE_FITTING=ON RBDL_BUILD_TESTS=ON
        cxx-flags: -DHAVE_CSTDDEF
        run-build: true
    - run: mkdir junit-reports
    - name: Run RBDL Core Test Suite
      run: ./build/tests/rbdl_tests -r junit > junit-reports/TEST-RBDL-CORE.xml
    - name: Run RBDL Balance Addon Test Suite
      run: ./build/addons/balance/tests/balance_tests -r junit > junit-reports/TEST-RBDL-BALANCE.xml
    - name: Run RBDL Geometry Addon Test Suite
      run: ./build/addons/geometry/tests/geometry_tests -r junit > junit-reports/TEST-RBDL-GEOMETRY.xml
    - name: Run RBDL URDF-Reader Addon Test Suite
      run: ./build/addons/urdfreader/tests/rbdl_urdf_tests -r junit > junit-reports/TEST-RBDL-URDF.xml
    - name: Run RBDL LuaModel-Reader Addon Test Suite
      run: ./build/addons/luamodel/tests/luamodel_tests -r junit > junit-reports/TEST-RBDL-LUAMODEL.xml
    - name: Run RBDL Muscle Addon Test Suite
      run: ./build/addons/muscle/tests/muscle_tests -r junit > junit-reports/TEST-RBDL-MUSLE.xml
    - uses: mikepenz/action-junit-report@v4
