name: C/C++ CI

on: [push, pull_request]

jobs:
  ubuntu-build:
    name: Build and Test RBDL + Addons
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install Build dependencies
      run: sudo apt-get install libeigen3-dev libboost-all-dev lua5.1 liblua5.1-0-dev catch2
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        cmake_args: -DRBDL_BUILD_ADDON_LUAMODEL=ON;-DRBDL_BUILD_ADDON_URDFREADER=ON;-DRBDL_BUILD_ADDON_GEOMETRY=ON;-DRBDL_BUILD_ADDON_BALANCE=ON
        submodule_update: ON
        run_tests: OFF
        unit_test_build: -DRBDL_BUILD_TESTS=ON
    - run: mkdir junit-reports
    - name: Run RBDL Core Test Suite
      run: ./build/tests/rbdl_tests -r junit > junit-reports/TEST-RBDL-CORE.xml
    - name: Run RBDL Balance Addon Test Suite
      run: ./build/addons/balance/tests/balance_tests -r junit > junit-reports/TEST-RBDL-BALANCE.xml
    - name: Run RBDL Geometry Addon Test Suite
      run: ./build/addons/geometry/tests/geometry_tests -r junit > junit-reports/TEST-RBDL-GEOMETRY.xml
    - name: Run RBDL URDF-Reader Addon Test Suite
      run: ./build/addons/urdfreader/tests/rbdl_urdf_tests -r junit > junit-reports/TEST-RBDL-URDF.xml
    - name: Run RBDL LuaModel-Reader Addon Test Suite
      run: ./build/addons/luamodel/tests/luamodel_tests -r junit > junit-reports/TEST-RBDL-LUAMODEL.xml
    - uses: mikepenz/action-junit-report@v4
